version: "3.7"
services:
        db:
                container_name: db
                image: mysql
                restart: always
                environment:
                        MYSQL_DATABASE: test 
                        MYSQL_USER: test
                        MYSQL_PASSWORD: test
                        MYSQL_ROOT_PASSWORD: root
                volumes:
                        - ./mysql/data:/var/lib/mysql:rw
                ports:
                        - "3306:3306"       
        app:
                container_name: php
                build:
                        context: ./php
                        dockerfile: dockerfile
                image: php:fpm
                depends_on:
                        - db
                ports:
                        - "9000:9000"
                volumes:
                        - ./nginx/html:/var/www/html
                environment:
                        PMA_HOST: db
                        PMA_USER: test
                        PMA_PASSWORD: root
        web:
                container_name: nginx
                build:
                        context: ./nginx
                        dockerfile: dockerfile
                depends_on:
                        - app
                volumes:
                        - ./nginx/html:/var/www/html
                        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
                ports:
                        - "80:80"
                        - "443:443"
                links:
                        - app
                restart: always
