FROM php:fpm

RUN apt-get update

RUN apt-get install libonig-dev
RUN docker-php-ext-install mbstring

RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install opcache
